# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 4267e2d3196c164cc3e902fb5155aca8ed468c20

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 4267e2d3196c164cc3e902fb5155aca8ed468c20

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/20/
Content-Type: application/json
Authorization: Token 4267e2d3196c164cc3e902fb5155aca8ed468c20

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2022-06-06
Content-Type: application/json

###

# добавление в избранные
POST {{baseUrl}}/advertisements/20/add_favourites/
Content-Type: application/json
Authorization: Token cac9e09cb931d0246dbb593d56b9fbb16f1d36e1

###


# список избранных сообщений
GET {{baseUrl}}/advertisements/list_favourites/
Content-Type: application/json
Authorization: Token cac9e09cb931d0246dbb593d56b9fbb16f1d36e1

###